#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/01752f86-d383-4bbc-8aeb-53b1d2ff117c/ # 
title: MuleCiCD

/cicd:
  get:
    body:
      application/json:
        type: string
        example:
          "HelloWorld CICD"